language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: ./vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
