# PHP CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # run tests!
      - run: vendor/bin/phpunit --verbose

      # store artifacts
      - store_artifacts:
          path:  build/coverage.xml

      # upload coverage
      - codecov/upload:
          file: build/coverage.xml

workflows:
  version: 2.1
  test:
    jobs:
      - test
